language: node_js
node_js:
- '9.2'
branches:
  only:
  - master

script:
- npm run generate:gh-pages
- cd dist
- git init
- git add .
- git commit -m "Deploy to Github Pages"
- git push --force --quiet "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" master:gh-pages > /dev/null 2>&1
