#.travis.yml

language: node_js
node_js:
  - "9.2"

branches:
  only:
    - master

before_script:
  - npm run generate:gh-pages

script:
  - npm run deploy

notifications:
  email:
    on_failure: change
    on_success: change
